### PR TITLE
Adjust Kafka version

### PR DESCRIPTION
**Pull request by jroessl**
Adjust the Kafka version in order to work with the current Spark version 2.3.2.

### CODE REVIEW

**Comment by mineo** [comment]
Thanks for the PR! Note that the Db2 Warehouse container currently ships Spark 2.3.0 instead of 2.3.2, so maybe we should use the assembly for 2.3.0 here?

**Comment by jroessl** [comment]
> 
> 
> Thanks for the PR! Note that the Db2 Warehouse container currently ships Spark 2.3.0 instead of 2.3.2, so maybe we should use the assembly for 2.3.0 here?

Unfortunately the assembly 2.3.0 does not work and throws the same exception.

**Comment by ToniBollinger** [comment]
You should include in this pull request the changes required in dashdb_analytic_tools/dashdblocal_notebooks/iot_producer/Dockerfile  needed to adjust the Zookeeper and Kafka version in the IoT producer Docker image.

**Comment by jroessl** [comment]
> 
> 
> You should include in this pull request the changes required in dashdb_analytic_tools/dashdblocal_notebooks/iot_producer/Dockerfile needed to adjust the Zookeeper and Kafka version in the IoT producer Docker image.

Done

**Comment by ToniBollinger** [comment]
Looks good!

**Review by ToniBollinger — APPROVED** [review]

**Pull request merged**
